# Generated by Django 2.1.3 on 2018-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20181113_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='buysell',
            name='currUser',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
