# Generated by Django 2.1.3 on 2018-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20181203_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='userName',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='lost',
            name='userName',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='rent',
            name='userName',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='to_let',
            name='userName',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
